### ISSUE TITLE
Nothing is happening when submit is clicked on the registeration form

### ISSUE THREAD

**Issue by meniscus44** [adrianhajdin/healthcare#22]
No error is seen in the console. I also tried to console log inside the onSubmit function but nothing is logged, so the onSubmit function  is not triggering. Not sure what the issue is. Link to my repo https://github.com/meniscus44/careplus 
Thanks in advance

**Comment by ShadowFeather1861** [comment]
I think issue is in appwrite file for some reason process.env is not deconstructing the values correctly and you have to set endpoints manually.
client.setEndpoint("https://cloud.appwrite.io/v1").setProject("here project id").setKey("here api key.");

**Comment by nahor-28** [comment]
Yes, not working. I am stuck too. Is this a appwrite issue?

**Comment by bobbywilliamajor** [comment]
The problem is because PROJECT_ID and API_KEY environment variables are not been accessed in the browser.

Make the following modifications to your env.local file

``` javascript
NEXT_PUBLIC _PROJECT_ID ="********"
NEXT_PUBLIC_API_KEY = "**********"
```

Make the following to your appwrite.config.tsx

```javascript
export const {
    NEXT_PUBLIC_ENDPOINT: ENDPOINT,
    NEXT_PUBLIC_PROJECT_ID: PROJECT_ID,
    NEXT_PUBLIC_API_KEY: API_KEY,
    DATABASE_ID,
    PATIENT_COLLECTION_ID,
    DOCTOR_COLLECTION_ID,
    APPOINTMENT_COLLECTION_ID,
    NEXT_PUBLIC_BUCKET_ID: BUCKET_ID,
  } = process.env;
  ```

**Comment by nahor-28** [comment]
> @bobbywilliamajor did this but still not working. The submit button just loads and nothing happens, i get POST /200 message in the console but the data is not recorded in the appwrite patient collection.

it is working now. thank you. silly typo was the isssue.

**Comment by BalajiUmapathy** [comment]
@ bobbywilliamajor
i cant still fix the issue .it is no response. not loading too

**Comment by Teegreat** [comment]
> @ bobbywilliamajor i cant still fix the issue .it is no response. not loading too

Could you compare your code to mine to check for errors?

make sure the enum values for gender start with a lowercase and the names of your inputs correspond to your attributes on appwrite.

https://github.com/Teegreat/hospital-mgt/tree/3f5886da040d3f7afb8ffff2dc5c90ee5a7d5aa7

**Comment by milosmekota** [comment]
check if you are using "use server" in patient.actions.ts

**Comment by nihalsheikh** [comment]
Finally solved this error by adding: 'use server' on top of the patient.actions.ts file

**Comment by joules65** [comment]
@nahor-28 what was the typo? I'm having the same error. just a post-200

**Comment by theTechbug** [comment]
Nothing happens when the submit button is clicked on the registration form. It seems the issue is that the form lacks the 'use server' directive, which is necessary for proper functionality. Adding 'use server' should resolve the issue.

**Comment by amjarmed** [comment]
**For anyone still encountering this issue:**

Please double-check that the spelling and naming in the following locations are identical:

1. The `name` property in the `<CustomFormField>` component (`name=""`).
2. The field names defined in the `/validations.ts` file for `PatientFormValidation`.
3. The field names used in the `attributes` of the patient collection.

**Important:**  
The form validation schema `const form = useForm<z.infer<typeof PatientFormValidation>>` will prevent form submission if:
- The field names are not identical across these locations.
- There are duplicated field names.

Ensuring consistency in naming will resolve this issue.

**Comment by minhajahmd** [comment]
I am facing a similar issue 
when i click on the get started button on the register form 
literally nothing happens (not even the loading... appears on the button)
looks like the onSubmit is not getting triggered
